sequenceDiagram
autonumber
User->>CLI: Run CLI via terminal command
CLI->>User: Would you like to start: yes/no?
User-->>CLI: no
CLI-->>User: CLI exit process
User->>CLI: yes
CLI-->>FileSystem: Access Files Failure
CLI-->>User: CLI exit process
CLI-->>FileSystem: Access Files Success
loop
    FileSystem-->>FileSystem: ./package.json
end
Note right of File System: Check dependencies
loop
    FileSystem->>FileSystem: ./package.json
end
CLI-->>User: Great!